import Head from 'next/head';
import Link from 'next/link';
import Button from '../components/Button';

export default function NotFoundPage() {
  return (
    <>
      <Head>
        <title>404 - Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="flex flex-col items-center justify-center my-16 space-y-2 h-72">
        <h1 className="text-6xl font-semibold text-recandy-blue-700">Oh no!</h1>
        <h3 className="text-3xl ">This page doesn&apos;t exist.</h3>

        <div className="flex flex-row pt-12">
          <Link href={'/'}>
            <Button type="primary" textSize="sm">
              Back to Home
            </Button>
          </Link>
        </div>
      </div>
    </>
  );
}
