import Head from 'next/head';
import Image from 'next/image';
import Button from '../components/Button';
import FeaturesPoint from '../components/pages/Home/FeaturesPoint';

import ExploreIllus from '../public/assets/img/codemart_explore.svg';
import SafeIcon from '../public/assets/icons/home_safely_icon.svg';
import SearchIcon from '../public/assets/icons/home_search_icon.svg';
import ExploreIcon from '../public/assets/icons/home_src_icon.svg';
import ChatIcon from '../public/assets/icons/home_chat_icon.svg';
import FormInput from '../components/FormInput';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section
        id="hero"
        className="flex flex-row items-center justify-between px-32 my-32"
      >
        <div className="flex flex-col max-w-2xl space-y-12">
          <div className="space-y-4">
            <h1 className="!leading-snug text-5xl font-bold">
              Explore <span className="text-recandy-blue-600">Source Code</span>{' '}
              for your Business{' '}
              <span className="text-recandy-blue-600">Needs</span>
            </h1>

            <p className="max-w-lg text-recandy-gray-900">
              CodeMart is Source Code marketplace that allow Developer post
              their works and Customer to buy Developer code based on their
              needs and requirements.
            </p>
          </div>
          <div className="space-x-8">
            <a href="/codemart-frontend/browse">
              <Button type="primary">Buy a Source Code</Button>
            </a>
            <a href="/codemart-frontend/sell">
              <Button type={'outline'}>I&apos;m a Developer</Button>
            </a>
          </div>
        </div>
        <div>
          <Image src={ExploreIllus} alt={'Explore'} />
        </div>
      </section>

      <section
        id="features"
        className="flex flex-col items-center justify-center pt-16 pb-24 pl-32 pr-16 space-y-16"
      >
        <h2 className="text-4xl font-semibold text-center">
          We&apos;re here to Help
        </h2>

        <div className="flex flex-row space-x-8">
          <FeaturesPoint
            title="Explore Source Code"
            description="Explore Source Code from our marketplace and find the best one for your business needs."
            icon={ExploreIcon}
          />

          <FeaturesPoint
            title="Browse Source Code"
            description="Find source code that suit with your needs by browsing posted source code by developer."
            icon={SearchIcon}
          />

          <FeaturesPoint
            title="Pay Safely"
            description="Our payment system is using trusted Payment Gateway Midtrans."
            icon={SafeIcon}
          />

          <FeaturesPoint
            title="Chat With Developer"
            description="We provide communication service for developer and customer that allow to communicate each other."
            icon={ChatIcon}
          />
        </div>
      </section>

      <section
        id="contact-us"
        className="flex flex-row items-center justify-between py-32 pl-32 pr-48 bg-recandy-blue-50"
      >
        <div>
          <h3 className="text-4xl font-semibold">Stay in Touch with Us</h3>
          <br />
          <p className="text-recandy-gray-900">
            Ask us question so we can help you
          </p>
        </div>

        <form
          action=""
          className="flex flex-col w-1/3 px-8 py-12 space-y-4 rounded-md bg-recandy-white-0 drop-shadow-xl"
        >
          <FormInput id="fullname" type={'text'} placeholder={'Full Name'} />
          <FormInput id="email" type={'email'} placeholder={'Email'} />
          <FormInput id="phone" type={'text'} placeholder={'Phone Number'} />
          <FormInput id="subject" type={'text'} placeholder={'Subject'} />
          <Button type="primary" size={'lg'} textSize={'sm'}>
            Submit
          </Button>
        </form>
      </section>
    </>
  );
}
